language: cpp

before_install:
    - eval "${MATRIX_EVAL}"

install:
  # Install conan
  - pip install --user -q conan
  # Automatic detection of your arch, compiler, etc.
  - conan user
  
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"


script:
  - mkdir build && cd build
  - conan install .. --build=missing -s compiler.libcxx=libstdc++11
  - cmake ..
  - cmake --build .
  - ./bin/test_hello
